- hosts: builder
  roles:
    - openwisp.openwisp2-imagegenerator
  vars:
    basedir: /home/jenkins/workspace/nnxx-firmware
    openwisp2fw_ssl_lib: openssl
    openwisp2fw_source_dir: "{{ basedir }}/source"
    openwisp2fw_generator_dir: "{{ basedir }}/generator"
    openwisp2fw_bin_dir: /var/www/downloads.openwisp.org/nnxx-firmware/
    openwisp2fw_source_version: lede-17.01
    openwisp2fw_source_archs:
        - ar71xx
    openwisp2fw_source_feeds:
        - method: src-git
          name: packages
          location: https://github.com/gabri94/packages-2.git
          branch: lede-17.01
        - method: src-git
          name: luci
          location: https://github.com/openwrt/luci.git
          branch: lede-17.01
        - method: src-git
          name: targets
          location: https://github.com/openwrt/targets.git
          branch: master
        - method: src-git
          name: routing
          location: https://github.com/openwrt-routing/packages.git
          branch: lede-17.01
    openwisp2fw_organizations:
        - name: firenze
          flavours:
            - full_olsrd2
          openwisp:
            url: "10.150.22.22 "
            shared_secret: Secretn1nuxFlo1932
            unmanaged: "{{ openwisp2fw_default_unmanaged }}"
            verify_ssl: 0
